os: osx
osx_image: xcode12.2

# Build OM SDK JS using Node.js/NPM tools.
language: node_js
# Use latest Node.js LTS release.
node_js:
  - "lts/dubnium"

# https://docs.travis-ci.com/user/environment-variables
env:
  global:
    - VERSION_NUMBER=$(cat public/version.txt | tr -d '\n')
    - HOMEBREW_CASK_OPTS='--appdir=/Applications'

before_install:
  - brew update > /dev/null
  - brew install google-chrome --cask
  - google-chrome --version
